//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denomica.Text.Json.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Denomica.Text.Json.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;glossary&quot;: {
        ///    &quot;title&quot;: &quot;example glossary&quot;,
        ///    &quot;GlossDiv&quot;: {
        ///      &quot;title&quot;: &quot;S&quot;,
        ///      &quot;GlossList&quot;: {
        ///        &quot;GlossEntry&quot;: {
        ///          &quot;ID&quot;: &quot;SGML&quot;,
        ///          &quot;SortAs&quot;: &quot;SGML&quot;,
        ///          &quot;GlossTerm&quot;: &quot;Standard Generalized Markup Language&quot;,
        ///          &quot;Acronym&quot;: &quot;SGML&quot;,
        ///          &quot;Abbrev&quot;: &quot;ISO 8879:1986&quot;,
        ///          &quot;GlossDef&quot;: {
        ///            &quot;para&quot;: &quot;A meta-markup language, used to create markup languages such as DocBook.&quot;,
        ///            &quot;GlossSeeAlso&quot;: [ &quot;GML&quot;, &quot;XML&quot; ]
        ///          },
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json01 {
            get {
                return ResourceManager.GetString("json01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;menu&quot;: {
        ///    &quot;id&quot;: &quot;file&quot;,
        ///    &quot;value&quot;: &quot;File&quot;,
        ///    &quot;popup&quot;: {
        ///      &quot;menuitem&quot;: [
        ///        {
        ///          &quot;value&quot;: &quot;New&quot;,
        ///          &quot;onclick&quot;: &quot;CreateNewDoc()&quot;
        ///        },
        ///        {
        ///          &quot;value&quot;: &quot;Open&quot;,
        ///          &quot;onclick&quot;: &quot;OpenDoc()&quot;
        ///        },
        ///        {
        ///          &quot;value&quot;: &quot;Close&quot;,
        ///          &quot;onclick&quot;: &quot;CloseDoc()&quot;
        ///        }
        ///      ]
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string json02 {
            get {
                return ResourceManager.GetString("json02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;widget&quot;: {
        ///    &quot;debug&quot;: &quot;on&quot;,
        ///    &quot;window&quot;: {
        ///      &quot;title&quot;: &quot;Sample Konfabulator Widget&quot;,
        ///      &quot;name&quot;: &quot;main_window&quot;,
        ///      &quot;width&quot;: 500,
        ///      &quot;height&quot;: 500
        ///    },
        ///    &quot;image&quot;: {
        ///      &quot;src&quot;: &quot;Images/Sun.png&quot;,
        ///      &quot;name&quot;: &quot;sun1&quot;,
        ///      &quot;hOffset&quot;: 250,
        ///      &quot;vOffset&quot;: 250,
        ///      &quot;alignment&quot;: &quot;center&quot;
        ///    },
        ///    &quot;text&quot;: {
        ///      &quot;data&quot;: &quot;Click Here&quot;,
        ///      &quot;size&quot;: 36,
        ///      &quot;style&quot;: &quot;bold&quot;,
        ///      &quot;name&quot;: &quot;text1&quot;,
        ///      &quot;hOffset&quot;: 250,
        ///      &quot;vOffset&quot;: 100,
        ///      &quot;alignment&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json03 {
            get {
                return ResourceManager.GetString("json03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;web-app&quot;: {
        ///    &quot;servlet&quot;: [
        ///      {
        ///        &quot;servlet-name&quot;: &quot;cofaxCDS&quot;,
        ///        &quot;servlet-class&quot;: &quot;org.cofax.cds.CDSServlet&quot;,
        ///        &quot;init-param&quot;: {
        ///          &quot;configGlossary:installationAt&quot;: &quot;Philadelphia, PA&quot;,
        ///          &quot;configGlossary:adminEmail&quot;: &quot;ksm@pobox.com&quot;,
        ///          &quot;configGlossary:poweredBy&quot;: &quot;Cofax&quot;,
        ///          &quot;configGlossary:poweredByIcon&quot;: &quot;/images/cofax.gif&quot;,
        ///          &quot;configGlossary:staticPath&quot;: &quot;/content/static&quot;,
        ///          &quot;templateProcessorClass&quot;: &quot;org.cofax.WysiwygTemp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json04 {
            get {
                return ResourceManager.GetString("json04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;menu&quot;: {
        ///    &quot;header&quot;: &quot;SVG Viewer&quot;,
        ///    &quot;items&quot;: [
        ///      { &quot;id&quot;: &quot;Open&quot; },
        ///      {
        ///        &quot;id&quot;: &quot;OpenNew&quot;,
        ///        &quot;label&quot;: &quot;Open New&quot;
        ///      },
        ///      null,
        ///      {
        ///        &quot;id&quot;: &quot;ZoomIn&quot;,
        ///        &quot;label&quot;: &quot;Zoom In&quot;
        ///      },
        ///      {
        ///        &quot;id&quot;: &quot;ZoomOut&quot;,
        ///        &quot;label&quot;: &quot;Zoom Out&quot;
        ///      },
        ///      {
        ///        &quot;id&quot;: &quot;OriginalView&quot;,
        ///        &quot;label&quot;: &quot;Original View&quot;
        ///      },
        ///      null,
        ///      { &quot;id&quot;: &quot;Quality&quot; },
        ///      { &quot;id&quot;: &quot;Pause&quot; },
        ///      { &quot;id&quot;: &quot;Mute&quot; },
        ///      null,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json05 {
            get {
                return ResourceManager.GetString("json05", resourceCulture);
            }
        }
    }
}
